# Generated by Django 6.0.4 on 2026-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_remove_category_icon_url_category_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="category",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="restaurants", to="restaurants.category"
            ),
        ),
    ]
