# Generated by Django 6.0.4 on 2026-05-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_menuitem_category"),
        ("restaurants", "0004_remove_restaurant_category_restaurant_categories"),
    ]

    operations = []
